### ISSUE TITLE
Updating Developer Section For Windows

### ISSUE THREAD

**Issue by MadhukarMoogala** [cyrillef/node-red-node-forge#1]
## Developing node-forge extension on Windows  for node-red

- Install all the required tools and configurations using Microsoft's [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) using `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).
- Clone [node-red](https://github.com/node-red/node-red) repo: ```git clone https://github.com/node-red/node-red.git```
- Clone this repo: ```git clone https://github.com/cyrillef/node-red-node-forge.git```
- ```cd node-red```
- Install the Forge node in node-red ```npm install ../node-red-node-forge```
- Install dependencies ```npm install```

**Comment by DirkSliepenbeek** [comment]
### **Please clarify where and how you put in your client_id and client_secret**

From the video example it is not completely clear how/where you specify the client_id or the client_secret, it seems like you do it before you use node-red, but that is not very clear explained. 

Is it also possible to do the forge authentication within forge? I tried this for a few hours now, but cannot get it up and running.

**Comment by cyrillef** [comment]
You can either create a generic credential node, or attach credentials to each nodes. In both case you need to create a credential configuration. See the steps here https://youtu.be/4YOS8r_Dn0o?t=934 - it contains the basics steps to configure credential nodes, and the authentication. Note I am using system variables to have my key, but you may want to copy paste them instead.
