### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by huvec** [cyrillef/node-red-node-forge#2]
Hi, 
I am following the youtube video and when i run, it comes up with numerous of the messages

node: d11e45dc.f66208
msg : string[25]
"Missing Forge credentials"

and the last message is
"RangeError: Maximum call stack size exceeded"

Please help.
Thanks

**Comment by cyrillef** [comment]
Can you provide your sample (export your flow as text and I'll debug it)

**Comment by cyrillef** [comment]
@huvec - this is fixed in version v0.0.5
the bug was that you code may have run before the Autodesk server had a chance to return a token. I updated to code to wait for this.
