### ISSUE TITLE
Upload from msg.payload file buffer

### ISSUE THREAD

**Issue by BerndGewehr** [cyrillef/node-red-node-forge#4]
When trying to combine different APIs it often comes to a point where you fetch a file from one API and want to put it to another one.

As far as I understood so far, the OSS upload action does not support uploading from a file buffer from the message object. 

Can you provide assistance on how to do such uploads or how to solve that problem otherwise?

**Comment by cyrillef** [comment]
I posted a Viewer sample in the latest version - v0.0.4

**Comment by cyrillef** [comment]
I update the package and rewrote the viewer sample to include a file upload. Start with /select.html
You need to make sure the settings are ok on the Settings node. The bucket name should be unique across all accounts, so choose something unique.
